### ISSUE TITLE
All values on android is strings

### ISSUE THREAD

**Issue by johankasperi** [didomi/react-native#120]
Because of this line https://github.com/didomi/react-native/blob/8a2a804091e5ab1cbd699a9d3629201587d7004f/android/src/main/java/com/reactnativedidomi/DidomiModule.kt#L312 all values on android is strings. For example when using `getDidomiUserStatus().vendors["example vendor"].enabled` the value is `"true"` or `"false"` instead of a boolean that your type definition says that it should be.

I'm using version 2.4.0.

Thank you!

**Comment by pmerlet-at-didomi** [comment]
Hello @johankasperi , thanks for your feedback. We'll make sure to fix this in the next release.
