### ISSUE TITLE
Android SDK 34

### ISSUE THREAD

**Issue by cfadeuilhe** [didomi/react-native#123]
Hello.
Could you add the property 'namespace' in you Android build.gradle, to be compatible with Android SDK 34 ?

android {
    namespace 'com.reactnativedidomi'
    ...
}

From end of August, we will not be able to publish any Android app if we do not target version 34 of Android SDK, so I am updating my company's app and I get this error:
>A problem occurred configuring project ':didomi_react-native'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   >  Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

I am using @didomi/react-native last version 2.5.0

Hope it's clear enough.
Thanks in advance

**Comment by nicolas-chaix-didomi** [comment]
Hello @cfadeuilhe the fix is available with https://github.com/didomi/react-native/releases/tag/2.6.0
