### ISSUE TITLE
Could not find com.iab.gdpr_android:gdpr_android:1.0.1

### ISSUE THREAD

**Issue by acominotto** [didomi/react-native#37]
Hello, 

with the retirement of jcenter, it would seem that your retired project of https://github.com/didomi/Consent-String-SDK-Android wasn't uploaded to Maven Central or an alternate repository, which creates an issue with the building of the app using the SDK.

Could you please fix this?

Thanks

**Comment by pmerlet-at-didomi** [comment]
Hello, can you check if the issue is still present with the latest release? ( https://github.com/didomi/react-native/releases/tag/1.7.0 )
It is using Android native sdk 1.59.1, so it should not need the jcenter repository anymore.

**Comment by acominotto** [comment]
That worked, thanks a lot :)
