### ISSUE TITLE
iOS getJavaScriptForWebView extra parameter

### ISSUE THREAD

**Issue by satopek** [didomi/react-native#5]
Hello, I was using the beta version of the library (thanks so much for the work, it helped a lot).
Now I tried this 1.0.0 release and found the same issues for iOS I had before.

These are the issues, after the pod install, we'll need to make some changes to these files:

react native complaints when doing:
`await Didomi.getJavaScriptForWebView();`
saying that it expecting one parameter but it got 0. In the header it's expecting `extra` but in the src we don't have any parameter:
```
getJavaScriptForWebView: (): Promise<string> =>
    RNDidomi.getJavaScriptForWebView(),
```
So I removed the extra parameter.
in **node_modules/@didomi/react-native/ios/Didomi.m**

I replaced:
```
RCT_EXTERN_METHOD(getJavaScriptForWebView:(NSString *)extra
                  resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject)
```
for:
```
RCT_EXTERN_METHOD(getJavaScriptForWebView:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject)
```

and in **node_modules/@didomi/react-native/ios/RNDidomi.swift**
I replaced:
```
@objc(getJavaScriptForWebView:resolve:reject:)
func getJavaScriptForWebView(extra: String = "", resolve:RCTPromiseResolveBlock,reject:RCTPromiseRejectBlock) {
	resolve(Didomi.shared.getJavaScriptForWebView(extra: extra))
}
```
for:
```
@objc(getJavaScriptForWebView:reject:)
func getJavaScriptForWebView(resolve:RCTPromiseResolveBlock,reject:RCTPromiseRejectBlock) {
	resolve(Didomi.shared.getJavaScriptForWebView(extra: ""))
}
```
I recovered the tracking popup in ios 14, this was in the beta version but not in this one. is it about an Apple Guideline?

```
didomiEventListener.onConsentChanged = { event in
	if #available(iOS 14, *) {
		if ATTrackingManager.trackingAuthorizationStatus == .notDetermined && !Didomi.shared.getEnabledPurposes().isEmpty {
			// Show the ATT permission request if the user has not made an ATT choice before AND the user gave consent to at least one purpose in the Didomi CMP
			ATTrackingManager.requestTrackingAuthorization { status in }
		}
	}

	self.sendEvent(withName: "on_consent_changed", body:"")
}
```

Thanks!

**Comment by felipe-saez** [comment]
Hi,

Thanks for submitting this issue and apologies for not getting back to you earlier. I think what's happening here is that we are missing one of these methods. We need to expose one that accepts the "extra" parameter and one that doesn't.

About ATT, I can see the code that you mention was there in 1.0.0 but it was commented out. Currently the expectation is that this is handled by app devs which would be consistent with the native iOS SDK.

We'll try to find the time to work on the getJavaScriptForWebView method as soon as possible.

Kind regards,

Felipe

**Comment by felipe-saez** [comment]
Hi Joan,

Version 1.2.0 has just been released. This version includes, among other things, a fix for the `getJavaScriptForWebView` method. Now you should be able to call it with and without the `extra` parameter.

Kind regards,

Felipe
