### ISSUE TITLE
"Empty" popup when translations are missing

### ISSUE THREAD

**Issue by Minishlink** [didomi/react-native#53]
Hello,

On an Android emulator API level 33, I get an "empty" popup
<img width="333" alt="image" src="https://user-images.githubusercontent.com/82368/187438314-904aadb1-a053-490c-a68d-57c8de817ec6.png">

Shouldn't the popup not open in that case? Can this happen only on emulators? 

Logcat shows
```
Cache file is not readable (/data/user/0/com.myapp/files/didomi_config_cache_xxx.json)
Cache file is not readable (/data/user/0/com.myapp/files/didomi_iab_config_v2)
```

**Comment by felipe-saez** [comment]
Hello Louis,

Could you please send these details to support@didomi.io including your `API Key` and `notice ID`?

Thanks,

Felipe

**Comment by Minishlink** [comment]
Hello, thanks. I updated the issue to better reflect the issue : when translations are missing, an empty popup appears. Expected behaviour would be either an error thrown or a fallback to the primary language.

**Comment by felipe-saez** [comment]
Hello Louis,

Thanks for doing that. Considering this subject concerns the Didomi Android SDK and not only the Didomi React Native SDK, I think the best way to communicate this feedback is through the support email address support@didomi.io, that way you can ask for updates on the topic later on. In any case I’ll make sure to pass this feedback to the product team.

Have a great day,

Felipe
