### ISSUE TITLE
Didomi initialization on iOS

### ISSUE THREAD

**Issue by Minishlink** [didomi/react-native#63]
Hello, 

Is there a specific reason why [here](https://github.com/didomi/react-native/blob/main/ios/RNDidomi.swift#L23), onReady/onError is called before initialization and not after. It seems weird, and on Android it's not the same workflow (onReady/onError is called after initialization).

Thanks,
Louis

**Comment by nicolas-chaix-didomi** [comment]
Thanks for your feedback @Minishlink.
The name of those events were not explicit. Those function were registering onReady and onError event listeners.

Those functions will be deleted among other fixes.

Regards

**Comment by Minishlink** [comment]
Does this mean we will be able to call setupUI/shouldConsentBeCollected at app startup at any time and the sdk will be ready to handle these without unexpected behavior ?
