### ISSUE TITLE
Export UserStatus interface

### ISSUE THREAD

**Issue by Geoffrey63** [didomi/react-native#84]
Hello, 

We use a custom Provider that store the userStatus in a state in our app.
To avoid types error we need to access to the `UserStatus` interface that is not exported in the index.tsx.
Is it possible to export it in the next version ?

**Comment by crebillon** [comment]
Hi @Geoffrey63 
Thank you for reaching out to Didomi's technical support and engineering teams!
We'll be adding the export of `UserStatus` to our backlog and will evaluate it for the next release.

**Comment by pmerlet-at-didomi** [comment]
Hello @Geoffrey63 , can you check if release 1.17.0 fixes the issue?
