### ISSUE TITLE
Change noticeId after init ?

### ISSUE THREAD

**Issue by budet-b** [didomi/react-native#86]
Hello, 

I have a question regarding multiple notice. I would like to change dynamically `noticeId` depending on a country change (vendors are different based on a country) but I don't find a way to do it. All I can do is `reset()` after country change and then re-init Didomi with the correct noticeId. My issue here is that I loose previous consent of previous notice. Is there a way to do it differently ?

Thanks!

**Comment by LeMourche** [comment]
Dear Benjamin,

I answered you at your email address via our Technical Support.

Kind regards,
